unit-tests-runner:
  before_script:
    - composer install --no-progress
  script:
    - vendor/bin/phpunit -c ./data/phpunit-test/phpunit.xml
  after_script:
    #- composer dump-autoload
    - echo "this is run after job"
  